# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  unity: game-ci/unity@1.3.0

workflows:
  create-unity-activation-file:
    jobs:
      - unity/create-activation-file:
          editor_version: 2021.3.2f1

