# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

workflows:

  build-unity-project:
    jobs:

      - unity/build:
          ...
          context: myProjectContext

